# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-25 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friends_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friended_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to='friends_app.User')),
            ],
        ),
    ]
