# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-25 20:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends_app', '0002_friend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='friended_by',
            new_name='user',
        ),
    ]
