# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-25 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends_app', '0003_auto_20171025_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='alias',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friend',
            name='email',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friend',
            name='name',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
    ]
