# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-25 21:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends_app', '0004_auto_20171025_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='user',
            new_name='friended',
        ),
    ]
